version: "3.8"
services:
  notebooks:
    build:
      context: .
      target: "satellite-image-segmentation-base"
    networks:
      - satellite_image_segmentation_default
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/notebooks
      - ./data:/home/jovyan/data
      - ./src:/home/jovyan/src

networks:
  satellite_image_segmentation_default:
    external: true
